spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
